name: Pr tag checker CI

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize  
      - labeled
      - unlabeled
    branches: [ "main" ]  
jobs:
  pr-tag-validator:
    runs-on: ubuntu-latest

    steps:
    - uses: rakesh4145/ML_AI@main
      with:
          regex: '"UCOA|Compliance|Category|Product Manager|Technical Product Manager"' 
          regex_options: 'i' 
          custom_non_match_error: 'valid tags  are ... UCOA | Compliance | Category | Product Manager | Technical Product Manager'
